### ISSUE TITLE
Java API

### ISSUE THREAD

**Issue by divThis** [divolte/divolte-collector#109]
Does a Java API currently exist for sending pixels to a Divolte cluster or is there a plan to support such a thing?

**Comment by friso** [comment]
Not right now. However, we're as we speak working on major changes that will add a server side endpoint to which you can POST JSON. The JSON payload is mapped onto Avro records using a mapping just like with the browser side generated events.

This would be the go to solution for logging events from other sources then the browser.

**Comment by divThis** [comment]
@friso This is great. Please let me know if I can be of any help testing this.

**Comment by friso** [comment]
@divThis Thanks. We hope to have something working before the end of the year. Are you running Divolte in production? We'd love to hear feedback once we have a release.

**Comment by divThis** [comment]
@friso Very cool. We do have Divolte deployed to production and are collecting 13 million pixels a day on average.

**Comment by divThis** [comment]
@friso I wanted to check in with you to see if I can help with the POST endpoint you mentioned. It looks like it's in progress in the dev/mobile-endpoint branch, but there hasn't been any progress for a while. I'm happy to lend a hand if I can, I just don't want to step on any work you have already done.

**Comment by friso** [comment]
@divThis Yeah, sorry for the delay. We are still working on this. The issue is that we're first reworking some of the internal threading. Because we now support multiple sources, mappings and sinks, this has increased a bit in complexity. I think picking up the work on `dev/mobile-endpoint` right now would be poor timing, as you'll have to make some changes afterwards when the new threading model is in there. I'll keep you posted!

**Comment by divThis** [comment]
@friso Ok. Thanks for the update. That all makes sense. Let me know if there's anything I can do to help!

**Comment by asnare** [comment]
The JSON-based endpoint was included in the 0.4 release via #129.
