### ISSUE TITLE
Let Kafka producer API provide flushing pool functionality?

### ISSUE THREAD

**Issue by cbsmith** [divolte/divolte-collector#112]
The KafkaFlushingPool's logic is duplicative of that provided by the Kafka producer API if you select an async producer. Is there something I'm missing or should the code be simplified to just invoke send on the producer?

**Comment by friso** [comment]
With the newer Kafka API (async), we can indeed rely on Kafka to take care of internal queueing before sending. I think this wasn't always the case.

We do however need one level of indirection between the mapping threads and the flushing threads, because otherwise something blocking Kafka flushing would also block HDFS flushing, which shouldn't be the case. In the bigger picture this exact behavior will depend on a number of other things as well.

Currently, we're working on supporting multiple sources (handlers, in the future not limited to just the javascript tracker) and multiple sinks. One decision for Divolte is to not support multiple HDFS and Kafka instances, but still in presence of distributed system failures, we need to make sure that unavailability of one doesn't influence the other. Practically, it means we've chosen to stop blocking on enqueuing internally (so max enqueue delay setting will be removed at some point) and never block a thread on enqueueing (so we drop the even asap on a full queue). There's some other interesting bits that probably need changing, such as the queue implementation that we use; the performance of ArrayBlockingQueue (due to its single lock) is becoming an issue for larger setups under substantial load.

In practice it means we'd like to have at least one thread for Kafka flushing separate from the request processing (mapping) to fully separate these concerns in terms of resources.

**Comment by cbsmith** [comment]
Yes, the API wasn't always there.

The async producer interface in Kafka should keep from blocking the thread the thread that invokes them. They return immediately with a Future. You can configure a callback handler if there is any logic you need to execute once a given request is completed. The callback will execute in the context of the producer's thread pool, so once you've called send(), there is really no reason for the request processing thread to get blocked.

Of course, in practice, you can consume the pool and end up with blocking there, but then KafkaFlushingPool using a blocking queue and therefore has the same exposure. The Kafka producer just has some smarter logic for buffering/amortizing the cost of sending up the messages, and is a bit more configurable (custom event handlers if divolte does have issues with it).

I'll see if I can patch together a suitable solution as a pull request.

**Comment by friso** [comment]
Currently, we block for a max of 1 second and then drop the event. In the near future, we'll never block at all and just drop the event as soon as enqueueing fails (when the queue is full). I don't know if Kafka's internal send queue is bounder or not, but if it isn't, we need to be defensive against it. If it is, it would either block or discard the message at some point, but I would imagine the former.

Also, it makes sense to look at the impact of whatever problem we're trying to solve here. Have you run the collector in a profiler under load?

**Comment by friso** [comment]
As an aside: it's better to start of these kinds of discussions on the [mailing list](https://groups.google.com/forum/#!forum/divolte-collector) and see if it requires an issue to be logged from there. It helps keep this space clean.

**Comment by asnare** [comment]
Earlier today we switched over to using the new Java-based async client. (See pull request #114.)

It turns out that although the API for the new Kafka client is async, sometimes the implementation blocks. Specifically:

 - When fetching/refreshing metadata.
 - When the internal buffers are full.

With this in mind we're going to leave the current buffering in place, although it's likely to change soon anyway when we move from the current concurrent queues to a disruptor ring-buffer.

**Comment by cbsmith** [comment]
It won't block when the buffers are full if set "block.on.buffer.full" to "false": http://kafka.apache.org/documentation.html#producerconfigs

The metadata will only block during initial contact with the Kafka cluster, and you can specify the maximum time to wait for it to get that metadata. I'd argue if you can't get initial contact with the cluster it is better for the collector not to accept connections.

**Comment by cbsmith** [comment]
Oh, never mind. I see you were using the 0.8.X API. In that case you want to set queue.enqueue.timeout.ms to 0.

**Comment by friso** [comment]
From the docs on retries:
  > Setting a value greater than zero will cause the client to resend any record whose send fails with a potentially transient error. *Note that this retry is no different than if the client resent the record upon receiving the error.*

This is in fact what we do, just from our own code.

Not accepting connections is not preferable. Also, there's no real difference between initial contact and subsequent ones; if Kafka was restarted for some reason or leader (re-)election happens, because of rolling restarts or up-/down-scaling, this is blocking. The design of the collector is such that when Kafka is not available (which it will be at some point, either due to network partitioning or failures), we keep a internal queue for a bit and start dropping events when that's exhausted. I appreciate that the Kafka client has a internal buffer as well, but it serves a different purpose: it's for batching the send queue when things actually work.

**Comment by cbsmith** [comment]
Yup. The Kafka's client retry/push mechanism is a bit smarter, but yes, same as what divolte does.

> Also, there's no real difference between initial contact and subsequent ones

Well, there is one important difference: the Kafka client won't block after an initial success, even if no messages can be delivered.

>  I appreciate that the Kafka client has a internal buffer as well, but it serves a different purpose: it's for batching the send queue when things actually work.

It serves both purposes, depending on how it is configured.
