### ISSUE TITLE
Support branch is a snapshot version

### ISSUE THREAD

**Issue by 0xR** [divolte/divolte-collector#118]
Branch `support/0.3` has version `0.4.0-SNAPSHOT` and as such it depends on `divolte-schema` `0.4.0-SNAPSHOT`. Because snapshot versions are not on mvn central it is not possible to install divolte-collector. 

I would expect that the `0.3` branch has version `0.3` and would depend on `divolte-schema` `0.3`.

**Comment by 0xR** [comment]
Downloading the release does work, but then I don't have it in a git repo.

**Comment by friso** [comment]
The support/0.3 branch is supposed to have 0.3.1-SNAPSHOT as version, as that is the next release version if we release from the support branch (the support branch is for back porting fixes against master into older releases; it's a bug fix branch). So the 0.4-SNAPSHOT was wrong. It's fixed now.

A SNAPSHOT version of Divolte never builds from source without first building and locally installing (as in `mvn install`) the schema, since we don't publish snapshot releases to Maven central. To get a working build from source either first `mvn clean install` the matching schema version or use a release source version (you can obtain one from checking out a release tag).

**Comment by 0xR** [comment]
:+1:
