### ISSUE TITLE
Cookies not set when cookie domain is empty

### ISSUE THREAD

**Issue by divThis** [divolte/divolte-collector#121]
When setting divolte.tracking.cookie_domain to an empty string, or relying on the default, no cookies are set. This appears to be due to the fact that in this instance, the JavaScript renders as `domain\x3d''`instead of omitting the domain parameter entirely.

**Comment by asnare** [comment]
I'm sorry for taking so long to get back to you about this. I just wrote a lengthy reply asking for clarification on where you're seeing this, before realising where the problem probably lies: I suspect you've configured the cookie domain using something like:
```hocon
divolte.tracking.cookie_domain = ''
```
instead of:
```hocon
divolte.tracking.cookie_domain = ""
```

The configuration format that we're using ([HOCON](https://github.com/typesafehub/config/blob/master/HOCON.md)) is a superset of JSON, and I think two of its features have conspired here to yield an _unanticipated result_:

1. String values don't need to be quoted.
2. Quoted strings use double-quotes (`"`), just like JSON. Single quotes (`'`) don't introduce a quoted string.

So really the first example is equivalent to:
```hocon
divolte.tracking.cookie_domain = "''"
```

… which means the server is configured to set cookies with a domain of `''` as you saw. Which won't work.

**Can you confirm this is or isn't the case?**

For the sake of posterity, I've decided to include part of my original reply which goes into why I was confused by this bug report, as well as a quick dive into how the tracking script works.

-------
[…] our automated test suite relies on the default configuration (where no domain is set), yet cookies are set and the tests pass. (There are currently some failing browser-based tests, but that's unrelated to this.)

In terms of how this all works:

1. The tracking script (`divolte.js`) has a global value (`COOKIE_DOMAIN`) that defaults to an empty string.
2. This is passed into both our calls to `setCookie()` as the last parameter.
3. If the value is _truthy_, we add the `domain=` bit to the cookie we set. An empty string should not trigger this.

So that would be straightforward. However:

1. At runtime, we compile and minify the tracking script using Google's [Closure Compiler](https://developers.google.com/closure/compiler/).
2. This lets us supply overrides for global script values, which we do for `COOKIE_DOMAIN` if a value is present in the configuration. (The meaning of 'is present' has changed recently.)
3. The closure compiler does a bunch of stuff including function versioning, constant propagation and dead code elimination. On master right now this results in the following code actually being served for the default domain setting:
```javascript
    function $setCookie$$($name$$60$$, $value$$74$$, $maxAgeSeconds$$, $nowMs$$) {
        $document$$1$$.cookie = $name$$60$$ + "\x3d" + $value$$74$$ + "; path\x3d/; expires\x3d" + (new Date($nowMs$$ + 1E3 * $maxAgeSeconds$$)).toUTCString() + "; max-age\x3d" + $maxAgeSeconds$$;
    }
```
The compiler has eliminated the domain-related branch entirely.

_At this point I started to think about what might lead to `domain\x3d''` appearing in here, and figured out it might be a configuration problem._

**Comment by divThis** [comment]
@asnare That was very helpful and helped resolve our issue. The conf file we were using was setting the value to `''` instead of `""`, which has a different result as you mentioned.

Perhaps it might be prudent to modify the source JavaScript to be more closely resemble the compiled version to avoid such issues with the Closure Compiler. For instance, the `setCookie` domain takes a cookie parameter. Since 'COOKIE_DOMAIN' is set staticly, it probably doesn't make sense for the `setCookie` function to even take this as a parameter.

**Comment by asnare** [comment]
@divThis I'm glad this helped pinpoint the issue you were having.

I also appreciate your suggestion, but won't be making those specific changes for the following reasons:

 - What the closure compiler generates will never be close to the code we write by hand, and isn't intended to be. They have different audiences: the code needs to be understood by humans, and correct. The closure compiler code doesn't have to be understood by humans, and I only quoted it as a proof that the problem lay elsewhere. Even if the closure compiler was not active, the original code would have evaluated the same way: a string containing two quote characters is _truthy_ and will therefore look like a domain.
 - I won't be removing the domain parameter from the call. In general code which accesses global variables is harder to understand and reason about: functions which are 'pure' (i.e. no global reads or side-effects) are almost always better for long term maintainability.

Instead I think there's something to be said for improving the validation of that configuration value. We've recently changed the way the server configuration is loaded so this should be easier now. I've created issue #123 to track this.
