### ISSUE TITLE
Using divolte with hdfs verison 2.0.0

### ISSUE THREAD

**Issue by eqw3rty** [divolte/divolte-collector#124]
Tried to use divolte collector with old hdfs version 2.0.0-cdh4.7.0. It failed on start with this error

> Caused by: java.io.IOException: Failed on local exception: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).; Host Details : local host is: "localhost/192.168.11.142"; destination host is: "localhost":8020; 

Currently divolte collector uses 4.3.0 version for hdfs. Requirements says it support Hadoop 2.0. 
Replacing hadoop libraries inside lib folder doesn't help.

**Comment by friso** [comment]
That's a pretty old Hadoop, which is indeed binary incompatible with what we compile against. Have you tried building from source with a matching Hadoop version in the build.gradle?

**Comment by eqw3rty** [comment]
Building from source might be a good option. Thanks.
In case old hadoop officially unsupported I think issue can be closed.

**Comment by friso** [comment]
I don't think we have a ultimate stance on officially supported Hadoop versions at the moment. The thing is the Divolte code is against the 2.0 API version of Hadoop/HDFS client. Technically, all 2.x.x versions *should* be wire level compatible amongst each other, but your seeing clear evidence their not. This could also be because of distros merging stuff that doesn't go into the Apache release. I think building from source with updated Hadoop client deps has a good chance. Be sure to use the deps from the CDH maven repo when doing so.

Good luck.
