### ISSUE TITLE
avro-ipc.jar missing from Divolte binary distribution

### ISSUE THREAD

**Issue by aspruds** [divolte/divolte-collector#204]
Divolte divolte-collector-0.7.0.tar.gz does not contain avro-ipc-1.8.2.jar. As a result, avro-tools throws java.lang.NoClassDefFoundError: org/apache/avro/ipc/Responder. 

I was following the tutorial from http://divolte-releases.s3-website-eu-west-1.amazonaws.com/divolte-collector/0.7.0/userdoc/html/getting_started.html#looking-at-the-data

**Comment by friso** [comment]
Looks like a bug indeed. The `avro-ipc` dependency was previously never required for using `avro-tools`, but apparently now it is.

Meanwhile, have you been able to walk through the tutorial nonetheless? Otherwise [here](http://www.michael-noll.com/blog/2013/03/17/reading-and-writing-avro-files-from-the-command-line/) is a online howto for reading the contents of Avro files from the CLI.

**Comment by asnare** [comment]
Merging #213 should have resolved this.
