### ISSUE TITLE
How to make sure party_cookie for same user is exactly same across different sites ?

### ISSUE THREAD

**Issue by vamsiautomatad** [divolte/divolte-collector#236]
Hello,

I wanted to clarify this .

let's say that divolte is hosted on divolte.example.com/divolte.js

and 

test.com
test-example.com 

both have the divolte script  and sending events .

how can I make sure that party_cookie will be same for the same user visiting test.com and test-example.com 

Thanks  !

**Comment by friso** [comment]
That's inherently not possible, because of the way cookies work. Cookies are not sent across domains and additionally other restrictions apply based on which browser is being used and the privacy settings of individual users.

First party cookies can be used to track users' actions within one domain and subdomains when properly configured. Tracking across domains can at best be achieved using URL rewriting to pass information between the domains using query strings, so you can later correlate the events. In this case, you will still have different party identifiers across domains.

**Comment by vamsiautomatad** [comment]
Thanks @friso for the comment. 
the condition will be different if Cookie is set using HTTP Response headers right ?

**Comment by asnare** [comment]
I'm sorry to shut this down, but it's not really dealing with an issue to fix or a feature request.

For general discussion we have a [Google Group](https://groups.google.com/forum/#!forum/divolte-collector) that's a better forum than here.
