### ISSUE TITLE
Generating a UUID possible in groovy mapping?

### ISSUE THREAD

**Issue by DaveSlinn** [divolte/divolte-collector#269]
I have the following in my mapping.groovy file:
```
mapping {
    map UUID.randomUUID().toString() onto 'id'
    map eventId() onto 'eventId'
    ....
}
```
But the result is every value of id is the same UUID.  I know divolte is already making a unique eventId that I can access, but is there also a way to put a UUID on every event?

**Comment by DaveSlinn** [comment]
I should note that I have read the "Understanding the mapping process" and know that it is evaluated once at startup, but I'm obviously not sure how I would implement something like this.

**Comment by friso** [comment]
Right, so indeed the fact that the mapping script is only evaluated once on startup is the reason that you're seeing the same value for all events. The script is more a configuration language than a place to hook in user code at runtime.

Internally, the mapping process depends largely on a type called `ValueProducer` defined in [`DslRecordMapping`](https://github.com/divolte/divolte-collector/blob/master/src/main/java/io/divolte/server/recordmapping/DslRecordMapping.java). Whenever you use a mapping construct in the Groovy script, some instance of a `ValueProducer` is created and that instance is subsequently used to do the actual mapping for each event. The `ValueProducer` implementations are internal to Divolte.

As a hack, it is possible to actually define and reference a specialised `ValueProducer` implementation within the Groovy script, which basically acts as a way to hook user code into the mapping process. Divolte doesn't support this out of the box, because of all the potential (performance) issues with user code executing as part of the mapping process. But it is possible.

A better option would obviously be to create Divolte support for a UUID value producer internally and add this as a construct to the mapping DSL. I don't see any reasons against this, if it proves helpful for some use cases. UUIDs are nicely ubiquitous and parseable by many runtimes. The reason that Divolte uses a custom format for identifiers are related to some parts of the implementation, but adding some additional unique identifier to events doesn't really hurt in any way.

**Comment by DaveSlinn** [comment]
Thanks for the info. I agree that including a built-in uuid() function in divolte. I wish I was a more competent java programmer and could add this, but it's definitely outside of my current capabilities. We will likely have to rely on a kafka stream to transform the events from their divolte ones into ones that match our desired end schema (which, by the way, is to have them conform to the emerging Cloud Event spec), which includes the complex schema I asked about in #267. The UUID is a proposed value for the required id field. We could use the eventid, but our other services producing ids would likely be using the UUID format.
