### ISSUE TITLE
Kafka Topic partitions best practice

### ISSUE THREAD

**Issue by MrMoronIV** [divolte/divolte-collector#330]
How many partitions would be considered as best practice for the clickstream topic?

Does it matter if it is more than one? Or does it have to be exactly one to make sure the events are read in exact order by consumers?

**Comment by krisgeus** [comment]
Order of events only matters per visitor. Party id is used as message key if I’m not mistaken. So you can have as much partitions as you want. 
36 is my preferred number because it can be easily divided in 1,2,3,4,6,9,12 and 36 so consumers have lots of options to evenly spread the reading 1 or more partitions
