### ISSUE TITLE
bin/avro-tools location

### ISSUE THREAD

**Issue by bbrumi** [divolte/divolte-collector#70]
Specify that the command 

    find /tmp/*.avro -name '*divolte-tracking-*.avro' | sort | tail -n1 | xargs bin/avro-tools tojson --pretty

should be called from where divolte is installed. If you change to a different terminal and are at a different path bin/avro-tools is not found

**Comment by asnare** [comment]
So, I'm not sure this is wrong, per se. This comes from the _Getting Started_ guide and earlier in the walk-through the user should be changing to the directory where they've unpacked Divolte.

During a recent tidy-up (0c982ac29b871244180264b2b6225bc70be97c85) this was changed slightly so that we now ask the user to run `./bin/avro-tools` which should be a little clearer, and work when the user doesn't have `.` on their shell path.
