### ISSUE TITLE
Divolte-collector start script raises exception on Ubuntu

### ISSUE THREAD

**Issue by NielsZeilemaker** [divolte/divolte-collector#77]
While attempting to start the divolte collector using it's startup script I got an exception saying:
"Can't shift that many" caused by this line
https://github.com/divolte/divolte-collector/blob/master/src/scripts/divolte-collector#L46

Changing the first line to bash instead of sh fixed it as suggested by
http://john.parnefjord.se/node/71

**Comment by asnare** [comment]
Hi Niels,

Thanks for reporting this.

Although the error message is the same, I think the root cause is different to the article you mention: it's due to the way we declare the shell function. Unfortunately we use a syntax that Bash understands, but not all Bourne Shells. Because it's not recognized as a function, the body executes immediately which triggers the error message you saw.

I'll commit a fix shortly.
